# need to run dotnet tool install -g dotnet-reportgenerator-globaltool
# Documentation:
#     https://reportgenerator.io/usage
#     https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=windows
#
# removes the previous coverage information     
set -euo pipefail

rm -rf ./coveragereport
rm -rf ./coverage

# runs the unit tests and stores coverage info in the coverage directory
#dotnet test --collect:"XPlat Code Coverage"  --settings "settings.runsettings" --results-directory="./coverage"

#dotnet test '-p:ExcludeByAttribute="Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute"' '-p:CollectCoverage=true' '-p:CoverletOutputFormat=cobertura' '-p:CoverletOutput=./coverage'
#dotnet clean

dotnet-coverage collect --settings "settings.runsettings" --output-format "cobertura" "dotnet test"

# generates a report named index.html from the coverage report generated by Xunit during unit testing
reportgenerator                                         \
    "-reports:output.cobertura.xml"                     \
    -targetdir:"coveragereport"                         \
    -reporttypes:"HtmlInline_AzurePipelines_Dark;Badges"\

# uses git to open up report automatically
git web--browse "./coveragereport/index.html"