/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IProbeBehavior_targetMember1 | IProbeBehavior_targetMember2}
 */
// @ts-ignore
export function createIProbeBehavior_targetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIProbeBehavior_target;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IProbeBehavior_targetMember1}
 */
// @ts-ignore
export function createIProbeBehavior_targetMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIProbeBehavior_targetMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IProbeBehavior_targetMember2}
 */
// @ts-ignore
export function createIProbeBehavior_targetMember2FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIProbeBehavior_targetMember2;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IProbeBehavior}
 */
// @ts-ignore
export function createIProbeBehaviorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIProbeBehavior;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IProbeThresholds}
 */
// @ts-ignore
export function createIProbeThresholdsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIProbeThresholds;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProbeConfigAggregate}
 */
// @ts-ignore
export function createProbeConfigAggregateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProbeConfigAggregate;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProbeSchedule}
 */
// @ts-ignore
export function createProbeScheduleFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProbeSchedule;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIProbeBehavior(iProbeBehavior: Partial<IProbeBehavior> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "packetPayload": n => { iProbeBehavior.packetPayload = n.getStringValue(); },
        "target": n => { iProbeBehavior.target = n.getObjectValue<IProbeBehavior_targetMember1>(createIProbeBehavior_targetMember1FromDiscriminatorValue) ?? n.getObjectValue<IProbeBehavior_targetMember2>(createIProbeBehavior_targetMember2FromDiscriminatorValue); },
        "timeoutMs": n => { iProbeBehavior.timeoutMs = n.getNumberValue(); },
        "ttl": n => { iProbeBehavior.ttl = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIProbeBehavior_target(iProbeBehavior_target: Partial<IProbeBehavior_targetMember1 | IProbeBehavior_targetMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoIProbeBehavior_targetMember1(iProbeBehavior_target as IProbeBehavior_targetMember1),
        ...deserializeIntoIProbeBehavior_targetMember2(iProbeBehavior_target as IProbeBehavior_targetMember2),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIProbeBehavior_targetMember1(iProbeBehavior_targetMember1: Partial<IProbeBehavior_targetMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ipAddress": n => { iProbeBehavior_targetMember1.ipAddress = n.getStringValue(); },
        "targetType": n => { iProbeBehavior_targetMember1.targetType = n.getEnumValue<IProbeBehavior_targetMember1_targetType>(IProbeBehavior_targetMember1_targetTypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIProbeBehavior_targetMember2(iProbeBehavior_targetMember2: Partial<IProbeBehavior_targetMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "hostname": n => { iProbeBehavior_targetMember2.hostname = n.getStringValue(); },
        "targetType": n => { iProbeBehavior_targetMember2.targetType = n.getEnumValue<IProbeBehavior_targetMember2_targetType>(IProbeBehavior_targetMember2_targetTypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIProbeThresholds(iProbeThresholds: Partial<IProbeThresholds> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProbeConfigAggregate(probeConfigAggregate: Partial<ProbeConfigAggregate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "behavior": n => { probeConfigAggregate.behavior = n.getObjectValue<IProbeBehavior>(createIProbeBehaviorFromDiscriminatorValue); },
        "probeType": n => { probeConfigAggregate.probeType = n.getStringValue(); },
        "schedule": n => { probeConfigAggregate.schedule = n.getObjectValue<ProbeSchedule>(createProbeScheduleFromDiscriminatorValue); },
        "thresholds": n => { probeConfigAggregate.thresholds = n.getObjectValue<IProbeThresholds>(createIProbeThresholdsFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProbeSchedule(probeSchedule: Partial<ProbeSchedule> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "spread": n => { probeSchedule.spread = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
export interface IProbeBehavior extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The packetPayload property
     */
    packetPayload?: string | null;
    /**
     * The target property
     */
    target?: IProbeBehavior_targetMember1 | IProbeBehavior_targetMember2 | null;
    /**
     * The timeoutMs property
     */
    timeoutMs?: number | null;
    /**
     * The ttl property
     */
    ttl?: number | null;
}
export type IProbeBehavior_target = IProbeBehavior_targetMember1 | IProbeBehavior_targetMember2;
export interface IProbeBehavior_targetMember1 extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The ipAddress property
     */
    ipAddress?: string | null;
    /**
     * The targetType property
     */
    targetType?: IProbeBehavior_targetMember1_targetType | null;
}
export type IProbeBehavior_targetMember1_targetType = (typeof IProbeBehavior_targetMember1_targetTypeObject)[keyof typeof IProbeBehavior_targetMember1_targetTypeObject];
export interface IProbeBehavior_targetMember2 extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The hostname property
     */
    hostname?: string | null;
    /**
     * The targetType property
     */
    targetType?: IProbeBehavior_targetMember2_targetType | null;
}
export type IProbeBehavior_targetMember2_targetType = (typeof IProbeBehavior_targetMember2_targetTypeObject)[keyof typeof IProbeBehavior_targetMember2_targetTypeObject];
export interface IProbeThresholds extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface ProbeConfigAggregate extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The behavior property
     */
    behavior?: IProbeBehavior | null;
    /**
     * The probeType property
     */
    probeType?: string | null;
    /**
     * The schedule property
     */
    schedule?: ProbeSchedule | null;
    /**
     * The thresholds property
     */
    thresholds?: IProbeThresholds | null;
}
export interface ProbeSchedule extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The spread property
     */
    spread?: string | null;
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIProbeBehavior(writer: SerializationWriter, iProbeBehavior: Partial<IProbeBehavior> | undefined | null = {}) : void {
    if (iProbeBehavior) {
        writer.writeStringValue("packetPayload", iProbeBehavior.packetPayload);
        writer.writeObjectValue<IProbeBehavior_targetMember1 | IProbeBehavior_targetMember2>("target", iProbeBehavior.target, serializeIProbeBehavior_target);
        writer.writeNumberValue("timeoutMs", iProbeBehavior.timeoutMs);
        writer.writeNumberValue("ttl", iProbeBehavior.ttl);
        writer.writeAdditionalData(iProbeBehavior.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIProbeBehavior_target(writer: SerializationWriter, iProbeBehavior_target: Partial<IProbeBehavior_targetMember1 | IProbeBehavior_targetMember2> | undefined | null = {}) : void {
    serializeIProbeBehavior_targetMember1(writer, iProbeBehavior_target as IProbeBehavior_targetMember1);
    serializeIProbeBehavior_targetMember2(writer, iProbeBehavior_target as IProbeBehavior_targetMember2);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIProbeBehavior_targetMember1(writer: SerializationWriter, iProbeBehavior_targetMember1: Partial<IProbeBehavior_targetMember1> | undefined | null = {}) : void {
    if (iProbeBehavior_targetMember1) {
        writer.writeStringValue("ipAddress", iProbeBehavior_targetMember1.ipAddress);
        writer.writeEnumValue<IProbeBehavior_targetMember1_targetType>("targetType", iProbeBehavior_targetMember1.targetType);
        writer.writeAdditionalData(iProbeBehavior_targetMember1.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIProbeBehavior_targetMember2(writer: SerializationWriter, iProbeBehavior_targetMember2: Partial<IProbeBehavior_targetMember2> | undefined | null = {}) : void {
    if (iProbeBehavior_targetMember2) {
        writer.writeStringValue("hostname", iProbeBehavior_targetMember2.hostname);
        writer.writeEnumValue<IProbeBehavior_targetMember2_targetType>("targetType", iProbeBehavior_targetMember2.targetType);
        writer.writeAdditionalData(iProbeBehavior_targetMember2.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIProbeThresholds(writer: SerializationWriter, iProbeThresholds: Partial<IProbeThresholds> | undefined | null = {}) : void {
    if (iProbeThresholds) {
        writer.writeAdditionalData(iProbeThresholds.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProbeConfigAggregate(writer: SerializationWriter, probeConfigAggregate: Partial<ProbeConfigAggregate> | undefined | null = {}) : void {
    if (probeConfigAggregate) {
        writer.writeObjectValue<IProbeBehavior>("behavior", probeConfigAggregate.behavior, serializeIProbeBehavior);
        writer.writeStringValue("probeType", probeConfigAggregate.probeType);
        writer.writeObjectValue<ProbeSchedule>("schedule", probeConfigAggregate.schedule, serializeProbeSchedule);
        writer.writeObjectValue<IProbeThresholds>("thresholds", probeConfigAggregate.thresholds, serializeIProbeThresholds);
        writer.writeAdditionalData(probeConfigAggregate.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProbeSchedule(writer: SerializationWriter, probeSchedule: Partial<ProbeSchedule> | undefined | null = {}) : void {
    if (probeSchedule) {
        writer.writeStringValue("spread", probeSchedule.spread);
        writer.writeAdditionalData(probeSchedule.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}) : void {
    if (problemDetails) {
        writer.writeStringValue("detail", problemDetails.detail);
        writer.writeStringValue("instance", problemDetails.instance);
        writer.writeNumberValue("status", problemDetails.status);
        writer.writeStringValue("title", problemDetails.title);
        writer.writeStringValue("type", problemDetails.type);
        writer.writeAdditionalData(problemDetails.additionalData);
    }
}
export const IProbeBehavior_targetMember1_targetTypeObject = {
    IpAddress: "ipAddress",
} as const;
export const IProbeBehavior_targetMember2_targetTypeObject = {
    Hostname: "hostname",
} as const;
/* tslint:enable */
/* eslint-enable */
